language: go
go:
- 1.3.1
- tip
env:
- PATH=$HOME/gopath/bin:$PATH
script:
- make dep
- make build
- make test
notifications:
  email: false
  slack:
    secure: oU9UF09Vby9HGbqgbXen0lA5UYZC0N53TaQ8G8u4vJROXoQ5qTg/RIwGgGdAXxZ+pBVARSaxG2JWxUXb5s8/cyRP8Aiuguk+ODrKNq52Bu1hd9TogPsdNrSTLFFMRUoD5/R2AueQyRN+W2NL1pc5TjyW7eByDLlgCKxUXDVFq38=
