include $(GOROOT)/src/Make.inc

TARG=taipei
GOFILES=\
        bitset.go\
        files.go\
        metainfo.go\
        peer.go\
        torrent.go\
        upnp.go\
        dht.go\
        krpc.go
include $(GOROOT)/src/Make.pkg
